### ISSUE TITLE
[Bug] Server command line arguments are unquoted

### ISSUE THREAD

**Issue by schwartzaher** [mikiher/audiobookshelf-windows#6]
pkg/prelude/bootstrap.js:1926
      return wrapper.apply(this.exports, args);
                     ^
UNKNOWN_VALUE: Unknown value: Server\docker\local-abs\config
    at commandLineArgs (C:\snapshot\audiobookshelf\server\libs\commandLineArgs\index.js)
    at Object.<anonymous> (C:\snapshot\audiobookshelf\prod.js)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47 {
  value: 'Server\\docker\\local-abs\\config'
}

Ignore that it says docker. This is just a folder I keep these types of things in so I can go to them easily.

**Comment by mikiher** [comment]
Ah, I assume you have spaces in your data directory. 
Sorry about this. will fix right away.

**Comment by mikiher** [comment]
Fixed in [release 2.7.2.1](https://github.com/mikiher/audiobookshelf-windows/releases/tag/v2.7.2.1). 
Thanks for opening the bug.

**Comment by schwartzaher** [comment]
Thank you for fixing this so fast
